module.exports = {
  USER: 'user',
  COUNTRY: 'country',
  FAMILY_CARD: 'family_card',
  DISABILITY: 'disability',
  ROLE: 'role',
  OCCUPATION: 'occupation',
  MARRIAGE: 'marriage',
  FAMREL: 'famrel',
  RELIGION: 'religion',
  EDUCATION: 'education',
  GENDER: 'gender',
  PROVINCE: 'province',
  CIREG: 'cireg',
  DISTRICT: 'district',
  VILLARD: 'villard',
  POSTCODE: 'postcode',
  RW: 'rw',
  RT: 'rt',
  ADDRESS: 'address',
  USER_INFO: 'user_info',
};
